scriptevent farmersdelight:cooking_pot_recipe {"container":{"item":"minecraft:bowl"},"identifer":"crabbersdelight:bisque","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[[{"tag":"crabbersdelight:cooked_seafood"},{"tag":"crabbersdelight:raw_seafood"}],{"tag":"farmersdelight:is_onion"},{"tag":"farmersdelight:is_rice"},{"item":"minecraft:carrot"},{"item":"farmersdelight:milk_bottle"}],"result":{"item":"crabbersdelight:bisque"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:clam_bake","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"crabbersdelight:cooked_clam_meat"},{"item":"crabbersdelight:cooked_clawster"},{"item":"crabbersdelight:cooked_shrimp"},{"item":"minecraft:seagrass"},{"item":"minecraft:carrot"},{"item":"farmersdelight:onion"}],"result":{"item":"crabbersdelight:clam_bake"}}
scriptevent farmersdelight:cooking_pot_recipe {"container":{"item":"minecraft:bowl"},"identifer":"crabbersdelight:clam_chowder","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"crabbersdelight:cooked_clam_meat"},{"item":"farmersdelight:onion"},{"item":"minecraft:potato"},{"item":"farmersdelight:milk_bottle"}],"result":{"item":"crabbersdelight:clam_chowder"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:cooked_clawster","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"crabbersdelight:raw_clawster"}],"result":{"item":"crabbersdelight:cooked_clawster"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:cooked_crab","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"crabbersdelight:raw_crab"}],"result":{"item":"crabbersdelight:cooked_crab"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:cooked_shrimp","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"crabbersdelight:raw_shrimp"}],"result":{"item":"crabbersdelight:cooked_shrimp"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:cooked_shrimp","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"crabbersdelight:raw_clam_meat"}],"result":{"item":"crabbersdelight:cooked_clam_meat"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:crab_cakes","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"crabbersdelight:raw_crab"},{"item":"minecraft:bread"},{"tag":"farmersdelight:is_milk"},{"item":"minecraft:egg"},{"tag":"farmersdelight:is_onion"}],"result":{"item":"crabbersdelight:crab_cakes"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:seafood_gumbo","container":{"item":"minecraft:bowl"},"tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"crabbersdelight:raw_cclawster"},{"item":"crabbersdelight:raw_cshrimp"},{"tag":"farmersdelight:is_onion"},{"tag":"farmersdelight:is_rice"},{"item":"minecraft:porkchop"}],"result":{"item":"crabbersdelight:seafood_gumbo"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:stuffed_nautilus_shell","container":{"item":"minecraft:nautilus_shell"},"tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[[{"tag":"farmersdelight:is_cooked_fish"},{"item":"minecraft:cooked_cod"},{"tag":"minecraft:cooked_salmon"}],{"item":"minecraft:kelp"},{"item":"minecraft:kelp"},{"item":"minecraft:kelp"}],"result":{"item":"crabbersdelight:stuffed_nautilus_shell"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:jar_of_pickles","container":{"item":"minecraft:glass_bottle"},"tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"minecraft:sea_pickle"},{"item":"minecraft:sea_pickle"},{"item":"minecraft:sea_pickle"}],"result":{"item":"crabbersdelight:jar_of_pickles"}}
scriptevent farmersdelight:cooking_pot_recipe {"identifer":"crabbersdelight:shrimp_fried_rice","tags":["cooking_pot"],"priority":0,"time":200,"experience":1.0,"ingredients":[{"item":"farmersdelight:cooked_rice"},{"item":"farmersdelight:onion"},{"item":"crabbersdelight:shrimp"},{"item":"minecraft:carrot"}],"result":{"item":"crabbersdelight:shrimp_fried_rice"}}
scoreboard objectives remove  farmersdelight_crabbersdelight_cooking_pot